services:
  app:
    container_name: pandam-blog-app
    image: pandam-blog-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/workspace
    ports:
      - "5173:5173"
    command: pnpm dev
